# -*- coding: utf-8 -*-
__author__ = 'yao'

checkList = [
    {
        "authorSign":u"求关注 逗比 童子功段子手 新媒体 全机种游戏制霸 二线中产 鉴黄师",
        "questionID": u"",
        "noRecordFlag": 0,
        "authorLogo": u"./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/14f19e9dd3d0c0909861362809a55a09_s.jpg",
        "answerHref": u"http://www.zhihu.com/question//answer/",
        "authorName": u"",
        "commitDate": u"2015-06-14",
        "authorID": u"",
        "answerID": u"",
        "updateDate": u"2015-06-14",
        "answerCommentCount": 0,
        "answerContent": u"我决定经常看看这个问题，激励一下没落家族长子长孙的复兴斗志。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "知无不言，知无，不言。",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/2865e5cda3f544c5b3d0666b2e189bab_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "爷爷辈以上基本没听过，听我爸说的。<br><br>也算是个…大宅门的故事吧…有祖宅，挺大的，当年好几房一起住。我爸是嫡孙，按理说宅子该给他但是我爷爷带着他在南京也不常回去，所以那宅子给我爷爷的妹妹家里占了，我爸也没有想回去拿回来的意思。<br>我爷爷祖上也算是个X半城之类的人物…然而………是个木匠…是，没错，木匠！（喂不要小看木匠啊喂！整个城的木匠铺全是我家的啊喂！）那个年代的时候，搞木材还是比较赚钱的，然后我家祖上硬是靠搞木材成了城里首富…家里也算是书香门第，虽然是个木匠然而子女都接受了当时最好的教育了。<br>然而到我太爷爷这辈疏于管理，并且家里偏房啊亲戚太多，就有点四分五裂了。而且吧我爷爷那一辈的哥儿啊爷们都是提笼架鸟的主儿，天天吃喝玩乐，铺子都给了大奶奶（我爸他奶奶）打理，后来老人家岁数大了，正好那时候也正赶上那啥嘛，铺子都没留住（我们家明明就是个木匠啊喂！不是地主啊喂！没收这些干嘛啦！）然而大奶奶机智的把黄金还有很多钱放罐子里藏在树根下啦。后来风头过了一大家子就靠这几罐子过日子。粮食那简直有价无市，罐子里的硬货就越来越少啊，后来无力支撑家里几十口人和那么大个宅子的打理，就败了，或者说从收铺子开始就已经败了。<br>我爷爷也没有想要重新捡起祖上传下的活儿的打算。于是去了南京，老爷子也是挺传奇的…文革前在铁路局混的顺风顺水成了大领导，听我爸说他小时候出门都是车接车送，想买啥买啥，后来……X革老爷子站队出了事儿，就被弄进去了…家里就树倒猢狲散，老部下啊老邻居都只能表达一下精神上的安慰，实质上谁都没帮忙，房子都给收了，我奶奶带着几个姑姑和我爸过日子挺辛苦了，后来我爸接受不了那种从天堂掉地狱的生活，变得脾气特别暴躁，打架都下死手那种。后来我爸挺大了我爷爷才放回来，回来就各种补偿，我爸都没搭理他，那时候铁路局来人请我爷爷回去官复原职甚至更高，我爷爷都不去了，就只当个主任，天天蹲家里。<br>我挺小的时候爷爷就去世了，但是我记忆里老爷子脾气特别硬，永远都特别严肃，因为只有我算是真正家里的嫡系了，特别疼我，（我姑姑们现在也经常说我家XXX就你这一个咱们老刘家的人了。）然而我那时候小跟我爷爷一直距离不近，但是我爷爷每次看到我出手都特别大方，每次那毛爷爷给的简直了。然而那时候老爷子已经肺癌晚期了，他竟然还能刻个木头出来，也算是不负家传吧。哦貌似老爷子随手刻的那个木头画拿了全国金奖。<br><br>据我爸说他奶奶就是特别看重嫡庶还重男轻女，可能老时候大户人家都是这样，就是一大桌菜我爸一个人吃，平常满街窜要什么吃什么，我爸都饱了…，他几个堂兄弟饿的眼睛都发绿也只能站一边看他吃，我爸有次叫他们来吃，小男孩嘛都不大，推了下就过来吃了，正好大奶奶看见。除了我爸，全罚跪了，特别狠心，跪了一整天。<br><br>唉大户人家后期就是，家里都没钱了还得要硬撑着面子，实际上工人的钱都扣的特别紧了，对外还是死要面子，买买买那种。<br><br>我爷爷去世的时候我看过一次老家来的人，据说是我爷爷的妹妹，那真是，唯唯诺诺的，没有主心骨的样子，我太爷爷在的时候听太爷爷的，大奶奶在的时候听大奶奶的，大奶奶不在就全听我爷爷的，我爷爷不在就都听我爸的………据说那时候养得来的女孩子就是这样……………<br><br>有次我问我爸能不能把咱家宅子收回来，就算不住把东西卖卖都是分分钟全是钱啊，那些个雕花，那些个檀木，咱家到底是搞木材的，家里一水的都是好木头阿，随便拎个板凳出来都比现在外面买的什么红木家具好多了。<br><br>可惜败了就是败了，我爸说可怜他姑姑还是好几房的堂兄弟什么的，都住宅子里呢，收了他们怎么办，后来我就再也没问过了。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "→_→",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "……",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/12fecc398_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "祖传绝技一个字，穷……",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "祖传保镖，从爷爷的爷爷那代起就是。<br>现在海里主管警卫工作的是我三大爷。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/da8e974dc_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "自從太祖爺爺的爹鎮壓長毛之後、估計殺人太多、從此人丁不旺...當年他娶了十幾房姨太太六十多歲才生了一個、然後我太祖爺爺娶了六房也只生了一個、然後我太爺爺生了終於生了兩個可悲劇的是有個十幾歲不學好抽鴉片死了、然後我爺爺生了兩個有個四年XX餓死了、然後我爹不幸遇到了計劃生育..........所以、幾百年人家無非行善、殺人要不得.",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "前段时间听我太爷爷说的<br>我们这个村子吴姓的是从福建迁来的，在弋阳那边也有个分支，算到我这辈上是第七代<br>解放前是小地主<br>当年也有在县里做事的<br>在他的描述中，地主并不像书里说的那么可恶，太爷爷的奶奶勤俭持家，把对门的那块地买了下来。<br>太爷爷的妈妈没有因为打地主分田地被打倒，可能是之前待人也不错吧，她老人家在3年自然灾害那段岁月里没能抗下来。<br>我太爷爷从小读书成绩好，小学没读完，我爷爷就说家里负担不起那么多人念书，而你成绩比我好，然后就让太爷爷去念书，我太爷爷一直读到高中，他在三年自然灾害时期在学校里，有分配的食物所以好过一点。后来他被分到乡信用合作社，因为计划生育问题被下岗，至今没拿到国家的补贴，之后30-40年不得不在家务农。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/015d6a5b3fac07c74210d98da8363205_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "好希望看到家里是盗墓家族的",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "我家祖传酱油一百多年……爷爷的爷爷是在香港开工厂卖酱油鱼露的。爷爷的爸爸是在香港卖酱油兼卖大米爷爷是地下党以家里卖大米酱油鱼露做掩护的铺子为交通联络点。解放前加入军队，后来在地方进了食品厂继续老行业，后来当了市财政局的二把手，后来我爹开了食品公司。，高考后在更新吧。。。。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "画画。",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/da8e974dc_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "看到了就回一条吧，还是真的第一次主动想回，我们家传不算太久，但是我有几个朋友特别牛逼，现在都平淡了。<br>我们家是纯正的满族人，兴起的比较晚，纳兰明珠是最牛逼的，这家里都供有老画，撇开老祖宗不提，因为犯了错误，基本被清算的都比较惨，我们家这一支就回到了关外，然后，碌碌无为，不过代代都有教书先生，不知道为毛，辈分就不多说。后来清末出了几个挺厉害的出家人，我不清楚，爷爷讲过一回，唯一最清晰的是大爷爷给我讲的民国，那时候大清没了，旗人再也不是贵族了，纳剌家影响不大，反正也不是达官贵人，然后继续教书，但是这时候已经积累了好多代财富，基本属于一方大阀，张作霖去给我们家老先生送过温暖，老头还嫌人家不识字。<br>张学良曾经听过老爷子讲书，那还是很小的时候，但是老爷子特别固执，认为他们都挺没文化的，老太爷还是特认真的种地，干私塾，我们家私塾是向本地开放的，基本就属于当地小学中学。<br>后来的各个老爷子都开始干实业了，干了不少企业，但是依然很平淡，特别有意思的事其实在要打起仗来的时候，老爷子集合了一方乡勇，结果张作霖死了，东北是没什么像样的政府的，东北改旗之后，蒋秃头派了一群逗比当各个市长，少帅那时候很小，大帅曾想过这个事，大帅曾嘱咐人如果事变，来先生家问机。<br>当然一切都特别快，张后来的做法也不是老爷子的意思，但是老太爷没有离开，仍然带着一群人保家卫国也好，还是维护祖产也好。<br>日本人很快就占领了东北，当然老爷子作为乡绅还是很受所谓器重的，虽然打伤了几个日本兵，也就没啥事，但是私塾不让干了，老爷子彻底不干了，明知不可为，老爷子带着一部分家人去了当时的哈尔滨，因为他跟俄国一些人关系比较好，偷偷摸摸继续当先生，这就是大毅力，后来很早就去世了。<br>我太爷爷这代人基本都经历过那个时候，太爷爷算是很有钱的，也很有办法，据说会点啥，我也不清楚了，老爷子找人太爷爷一路跑到了北京，找了很多旧识。很少有人知道当时东北沦陷后的东北人民对日本人是多大的憎恨，但是日本兵太多了。找关系太爷爷也没有成功，光头的态度很不好，光头要打共产党。国军里面有很多家族旧识，然后太爷爷稀里糊涂的当了国军，但是他留了个心眼，填了个汉人名字，南征北战了很多年，在傅作义底下一直勤恳工作,傅作义晚年还和太爷爷见过面，这都是题外话了。<br>因为太爷爷不太会打仗，建功立业的机会倒是不多，反倒军纪挺好的，这个是出了名的，如果各位家里有熟悉可以问问，是哪个部队？话不多说了，国军很有意思，工龄到了自然升官，这中间有很多有意思的事，以后我再补充。<br>他运气好的像穿越过一样几乎没打过败仗，主要没咋打，清理土匪之类的干的多，卫景林是他在101时候好友，如果有后人应该还可以了解。<br>我太姥爷就更有意思了，他是历史上都查不到的人，他姓孙，是国父后代，有钱的大地主。但是却是过继的，我也不知道到底有没有这回事，他们家谱现在还有，姥爷是个特沉稳的人，从他身上真的能看到大家族的气势，无论多大事，不轻易发脾气，如果发脾气也是关系尊严，关系脸面，姥爷年轻就很能干，尽管穷了，他离开家的时候刚好斗地主，为了安全，他带着当时还是个红卫兵的姥姥跑到了东北，她们年龄相差大概十几岁，很牛逼的私奔。<br>未完待续。。。。。。。。。。",
        "answerAgreeCount": "3"
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "祖传把妹儿达人，段子手，自带桃花属性。<br>祖上是秦始皇，古姓嬴，伯益之后。 <br><br>爷爷的爸爸的兄弟，在那个封建的年代，好多女孩子寻死觅活的跟他，而且就算不娶都不打紧，只要在一起就行。<br>曾经没吃的，自己做假的木头枪，一人截下日本人的船……然后拿走所有的食物和物资。（家乡在江边）后来没吃的，就让所有人围坐一圈听他即兴讲笑话来排解饥饿。<br>爷爷的爷爷是农民，自己写剧本给人家演喜剧，也是各种即兴段子讲给大家听，结婚的时候有好多女孩子选择背井离乡离家出走寻死觅活……<br>我爹把妹儿达人，因为爷爷投机倒把卖八角五香 ，所以家里顿顿有肉吃，算是村里的富二代了吧。据我爹所说小时候就没做过农活……每天戴着墨镜扛着大录音机到处晃 后来不听话 进了少林寺学武 回来后好多女孩子蹲在家门口守着他 要嫁给他……后来我爹结婚的时候，好几个女孩子故意嫁给我爹的邻居就是为了每天看到我爹。现在这么大个年纪了，每次移动营业厅，银行，4S店只要有漂亮的小丫头，他总是可以逗的别人直不起腰来，然后顺利要到电话。你问我要电话干嘛？<br>当然是给我啦！<(￣）￣)>我可是要传宗接代的。话说上一个女朋友就是他在工地上电梯里找一个设计师妹子要到电话并且通过3分钟之内的交流把别人骗到了我家来了。∑( ° △ °|||)︴后来我问她为啥就跟着我爹这样一个陌生人来到我家！不怕是坏人吗！",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "a-Weibo",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/d17db06c206ad1b01fabeab52948df22_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "曾祖父继承祖传职业：农民，后来日军侵华被日本人抓去挖过战壕。到了爷爷这一辈，赶上解放战争，因为念过私塾，认识字，放羊的时候看到了八路军的宣传册，那个时候读书人都很理想化，后来就到县里当了粮油助理员，大概就是这么个职务，后来GCD势力发展了，派到民兵连当连长，反复被父亲提起来战绩就是爷爷带领一帮民兵去山里围捕了前国民党县保安团团长，类似于公安局局长。六二年父亲和奶奶被遣返回了农村劳动，文革的时候因为爷爷年轻的时候在日战区张家口做过生意，所以被打成了走资派，听父亲说以前家里还有爷爷和周恩来、刘少奇、胡耀邦的合影，（我猜应该是开会的大合照），但是后来由于各种原因找不见了，现在只剩一张和赵ZY的大合影。缅怀一下吧，到了我这一代见过最大的领导就是乡长了。<noscript><img data-rawheight=\"934\" data-rawwidth=\"1248\" src=\"http://pic3.zhimg.com/d047f6fdad8df3485702edb162a9111e_b.jpg\" class=\"origin_image zh-lightbox-thumb\" width=\"1248\" data-original=\"http://pic3.zhimg.com/d047f6fdad8df3485702edb162a9111e_r.jpg\"></noscript><img data-rawheight=\"934\" data-rawwidth=\"1248\" src=\"http://s1.zhimg.com/misc/whitedot.jpg\" class=\"origin_image zh-lightbox-thumb lazy\" width=\"1248\" data-original=\"http://pic3.zhimg.com/d047f6fdad8df3485702edb162a9111e_r.jpg\" data-actualsrc=\"http://pic3.zhimg.com/d047f6fdad8df3485702edb162a9111e_b.jpg\" style=\"width: 584px; height: 437.064102564103px;\">",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "嗯，我只知道没改姓之前，我姓爱新觉罗。点赞吧~",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "看到这个我也说说。姓氏是明朝皇帝赐姓，到我20几代了。有太多可以说的，想想还是随便写几条。听爷爷说，以前家里的地骑马早上出门到晚上沿路喝的水都是自己家的水井。从我往上5代还是6代出了个大败家子，两口子洗脚都用人奶(๑•ั็ω•็ั๑)，一夜输过18个家庙的地（一个家庙有多大的地我到现在也不知道），回老家上坟还要去看看的-_-||<br>解放前家里的银洋还是要大箱子装的，然后就遇到了打土豪斗地主抄家-_-||<br>到现在我为了一套房子只能拼命",
        "answerAgreeCount": "1"
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/da7422bc133fd26f43c6d37c369dc4de_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "爷爷的爷爷是个县官。<br>爷爷的爸爸是个比县官还小的官。<br>爷爷没官，有钱。<br>爷爷爱京剧，便买了一整套的京剧行当，兴起时就请班子到家里来唱，喝茶看戏，不亦乐乎。后来日本鬼子来了，就把这些东西埋院儿里逃命去了。后来做了木匠，远近闻名。<br>爸爸没官，没钱，有地，后来做小生意了。<br>我没官，没钱，没地，没工作。<br>———————————————————其实我想说的是…我祖上复姓独孤，汉武帝时…我讲完了。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "琅琊王",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "无法归类",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "./你的家传祖业，有什么精彩的内行故事吗？ - 知乎_files/d3ef0e50637847219a3f664e0a5fc458_s.jpg",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "",
        "commitDate": "2015-06-14",
        "authorID": "",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "张姓，名门之后。<br>祖上几代搬迁太多，<br>祖谱早已不知去向。<br><br><br>我很想知道自己从哪里来，<br>一个家族最大的悲哀应该是不知其历史了，已经被历史藏的太深。<br><br>随着家里长者的去世，很多故事再也不会知道，他们的记忆里都很少。<br><br>就这么在某一隅落地生根了。<br><br>就这样平静地奋斗下去吧。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "外公家里就是普通中农，解放以后，为了让二爷爷三爷爷读书，外公高中上了一年，死切摆列的跟着征兵队伍去了朝鲜，一个县里去了一个营，完整回来的一个连都不到，我外公因为年纪小，而且读过书直接做了通讯员，然后升了参谋，回西安认识我外婆，58年入学的西安师范的本科，孔子73代传人。<br>然后结果没多久，因为对印自卫反击战去了新疆，经历了文革，文革结束后外公升上校军衔，之后百万大裁军，新疆军区与兰州军区合并，外公去了新筹建的学校教书，一教20年，最后少将退休，现在专业技术三级，二级文职干部。据说是没怎么上过战场，但不知道没上过战场那一盒子勋章都哪来的。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "小时候在奶奶家待了几年 感觉就是富裕的小康家庭 奶奶在家是大掌柜的 爷爷特别惯着奶奶 就爱看看书 <br>后来才听爸爸说  他姥姥家里 以前是有祖传的产业 有酒楼 有当铺啥的 家里富裕的不得了 到后来战争时期 家里产业一夜全没了 就奶奶聪明把家里东西 什么银元 古董啥的全埋起来了 但是打击还是挺大的 爸爸他姥姥姥爷没了  我奶奶后来没钱了 就挖银元 用篮子拿着一篮一篮的卖 把弟弟妹妹养大 自己没看过书 但是家里的 都是什么 北外 军工大 什么毕业的（现在新华社 东北某市市委 还有老家的那个首富 我就见过一两回 后来去北京才见到那个舅爷）都是长大才知道 家里老宅子拆的时候 都是爸爸 大伯他们自己拆的（说是奶奶要求的）挖出来挺多东西（奶奶说都留给我们几个小辈当老婆本）对了 我奶奶说 我爸小时候上学 拿白面馒头换人家杂粮馒头 老把家里的肉啥的偷到学校去给小女朋友吃 ",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question//answer/",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": u"说起来还和楼上的李鸿章后裔有些渊源，那位楼主的太爷爷是李家焜吧。在下祖母的父亲，是浙江兰溪赵氏的后裔，赵氏是名门大族，明清赵氏出身的高官显贵无数。而祖母的曾祖父，就是招商局的人，而她的祖父是北洋政府交通部的官员，也是交通系的中坚成员。在孙传芳时代经常帮助孙采购军火和欧洲设备，后在北伐成功后不久就病死了。祖母的父亲是当时上海的显贵之一，授业恩师是晚清四大诗家的郑孝胥，有着很好的经史诗词功底，后来留学德国，回国后继承家业成为了上海首屈一指的大资本家，著名的金融家族席家缺钱都得问他借钱，例如上海东平路十号的爱庐就是他送给宋子文，宋子文继而转送给蒋介石夫妇的。他当时嫌弃淮海中路的祖宅阴森就在法租界毕勋路建了一栋宅子，当时耗费了150万大洋，就在法租界公董局旁边，如今是汾阳路花园酒店。说起来我的外曾祖父和外曾祖母倒是很感人，他们一见钟情，恩爱厮守，感情浓厚到无法言喻，后来外曾祖父意外得肺结核于1935年离世，外曾祖母悲痛不已殉情身亡。当时祖母才上初中，后来抗战爆发祖母跟着小姨去了重庆，说起来也奇特，祖母小姨的前男友是国民政府的张存仁少将，后来的军统重庆站副站长，重庆失守后他潜伏刺杀邓小平失败被处决。而他们俩是在上海念书的时候在和帮鲁迅一起卖书认识的，鲁迅还请他们在德大吃过饭，后来因为祖母小姨的男友是坚定不移的忠蒋派出卖了左翼文人导致多人被害从而分手的。而祖母的父亲刚好还当过一阵子张存仁的老师，后来抗战以后赵家其余亲人因为投靠了祖母母亲的家族从而被清洗几乎被灭门，毕勋路宅邸也被焚烧殆尽。祖母的外祖父是南洋革命党人，和陈璧君等人一起来的大陆，后来弃政从商，生下了一儿两女，汪精卫政府成立后陈璧君力邀祖母的外祖父参政，而且吉斯菲尔路12号就是她外祖父家，有着很好的安全保障，但后来没几年祖母的外祖父就被军统杀手刺杀了。不过祖母的小姨是反日的还加入了中统因而侥幸留命，她们感觉上海是伤心之地所以迁去了北平。后来国共战争爆发，祖母和她小姨因怕北平成了第二个长春从而逃难，但因战乱失去了联系，然后祖母就从北平流落到山西，当了一名中学老师后又嫁给了一名共军的复员军官，就是我的祖父。后来一直过的不算好也不算坏，谁也不知道她的身份，所以文革反右也安然度过，我父亲是连生了几个女儿后的长子，他读书的时候是文革刚过去，所以在他初高中时候祖母教导了我父亲不少，让他读了不少书，培养了他学术的兴趣，从而在之后成为了一名大学教员并创立了一所私立小学。我从小听着父亲和祖母讲述的琐闻，后来和父亲也去过上海旅游，他带着散步我提到过这些旧事，今天偶然看到就随口絮叨絮叨，也真的感觉中国近代历史真是奇妙深刻令人感慨唏嘘不已啊。<br><br><br><br>哦对，最后补上一个有意思的事，在下的祖母是张学良配偶赵四小姐的堂妹，她们都出身于兰溪赵氏。赵四小姐的父亲就是祖母的祖父帮扶上去的，而海关在汾阳路的那栋至今尚存的宅邸是祖母父亲贱价把院子的多余不规则部分的地皮卖给海关从而修建的。",
        "answerAgreeCount": "2"
    }
]