# -*- coding: utf-8 -*-

from base_test_function import *

__author__ = 'yao'

checkList = [
    {
        "authorSign": "一位愚蠢的自私生产者",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic2.zhimg.com/7d80921f66b99a05d53f0ffffbd15f7d_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/52601984",
        "authorName": "一片城荒枕碧流",
        "commitDate": YESTERDAY,
        "authorID": "yipian-cheng-huang-zhen-bi-liu",
        "answerID": "52601984",
        "updateDate": YESTERDAY,
        "answerCommentCount": 0,
        "answerContent": "据说我祖上姓姬，复姓轩辕。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "我在看你",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic2.zhimg.com/67830b584936fe1b01936c52dc56cf71_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/52393639",
        "authorName": "江东老范",
        "commitDate": "2015-06-23",
        "authorID": "fan-cheng-zhi",
        "answerID": "52393639",
        "updateDate": "2015-06-23",
        "answerCommentCount": 0,
        "answerContent": "祖上在北宋末年是丞相范宗尹，后随宋高宗南下，起初推举秦桧，后与之不和，被陷害辞官。至十六代范钦，抗倭有功，任明兵部右侍郎，与严嵩严世番父子不和，辞官回家，建造天一阁，宁波的标语书藏古今，港通天下，里前半句就是说的我们家族。然后避免不了文革的大浪潮，通通被赶出维系了几百年的家业，当时的借口居然是天一阁里的一个珍贵犀角杯不见了，怀疑是太爷偷的，本来就是我们家的东西哪有自己偷自己东西的道理，欲加之罪何患无词，太爷死的时候还喊着冤枉，然后就将天一阁收归国有，特殊时期毁掉的珍贵文物，历史资料，照片比比皆是，叹息文化的断层，家族的没落。前几年天一阁庆的时候，政府随意叫个海外的范氏后人某个大老板来阁里庆祝，大放厥词，真伪难辨。然后去范钦太公墓拜祭，我们虽然落魄，但也有自己的原则，直系亲属在那拜祭，一干政府官员及所谓范氏后人大老板只得在旁默默观看。范钦太公及至十六世到我，虽然有些梦想，但无奈家道中落，只得努力奋斗，多交朋友，静观其变。",
        "answerAgreeCount": "4"
    },
    {
        "authorSign": "一流三俗/二流摄影/三流排版",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic2.zhimg.com/03bfef722e693b8ff80ddd86367ab115_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/52334930",
        "authorName": "胡马兜",
        "commitDate": "2015-06-23",
        "authorID": "hu-ma-dou",
        "answerID": "52334930",
        "updateDate": "2015-06-23",
        "answerCommentCount": 0,
        "answerContent": "太爷爷是算命先生。<br>说到祖传其实也不算，因为不是本家祖上传下来的，而是从祖师爷哪儿传下来的。<br>祖师爷下过咒，不能传子孙的，只能收一个徒弟，徒弟学成时必瞎，师父必死。<br><br>我也是高三毕业才慢慢从父辈口中听到这些事。<br>当年我太爷爷是整个县城里面算是小有名气的先生。有自己的规矩，每天早上起来必须得吃三个蛋才开始算命，只在早上算，来早了候着来晚了没门。当时的县令也来算（我也忘了当时是不是叫县令…反正就是管着这个县的官吧…历史不好不想考察了），为了排队召了一堆兵从家门口排了一整条街。<br>打我爸记事时我太爷爷就是看不见东西的，说法是祖师爷的咒，真是个什么原理我也不知道了。。<br>手艺是不能传自家儿女的，当时有一个我爸叫伯伯的人来家里想拜师，我太爷爷不许，一是觉得天资不够，二是学成师父必死。那位伯伯就在家院子里跪了三天，最后太爷爷还是收下了他。<br>不出意外，学成之后那位伯伯就瞎了，太爷爷也就西去了。<br>正好赶上某个时间点，家里关于风水方面的存书全被烧掉了，爷爷也被关了起来。太爷爷下葬时上面发话不许立碑。<br><br>这些是在不同时间段听我爸和几个叔叔说的。<br>当时我心里是这样的：WTF！！？我家居然有这样的事儿？？？？<br><br><br>不过事情得追求眼见为实，我自己见到的事只有太爷爷的坟确实只是一个土堆，每次清明节上坟我都会找不到。<br>以及那位伯伯瞎了之后，娶了一个老婆，也跟着瞎了，我叫奶奶，这位奶奶每天都在门口晒太阳，什么也看不见，坐在那儿。<br><br>至于往后的到底有没有徒弟，我就没去考究了。<br><br>这个不是祖传，但是觉得蛮…鹅妹子嘤<br>所以我爸现在不相信这些算命先生，觉得不够格，我爸说算命是开了天眼的，眼睛自然就看不见了，现在的好多算命先生那是开钱眼。",
        "answerAgreeCount": "2"
    },
    {
        "authorSign": "崇尚传统文化",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic4.zhimg.com/03d322b6bf58e5d0769b5ee1afbeae17_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/52267068",
        "authorName": "曾长驿",
        "commitDate": "2015-06-22",
        "authorID": "ceng-chang-yi-4",
        "answerID": "52267068",
        "updateDate": "2015-06-22",
        "answerCommentCount": 0,
        "answerContent": "来听爷爷讲，祖上是地主，家里人丁兴旺，家底丰厚。很多做工的人，很多枪支弹药，还有大炮。但是有好多土匪，对我们的家业还有武器虎视眈眈，所以经常攻打来，那叫一个激烈啊，还好我们家有大炮，土匪们最怕这个，有次用大炮把土匪们炸死了几个，土匪们四散而逃……",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/52019713",
        "authorName": "匿名用户",
        "commitDate": "2015-06-20",
        "authorID": "coder'sGirlFriend~",
        "answerID": "52019713",
        "updateDate": "2015-06-20",
        "answerCommentCount": 0,
        "answerContent": "太爷爷当时在村子里面是兄弟五个。并称张家五虎，隔壁村李家也是大户兄弟俩当时混名李家二龙。两家火拼然后五虎战二龙。然后龙就没了。有了我爷爷以后太爷爷后来地主家当长工，地主家不给工钱反正就是有挺多事情在里面，太爷爷就东门进西门出。事情闹大了就闯关东了，家里的武术啊到我爸内一辈就不学了吧，嗯留下来的我就小时候见到过一把我太爷爷的刀。。。。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/51740386",
        "authorName": "匿名用户",
        "commitDate": "2015-06-18",
        "authorID": "coder'sGirlFriend~",
        "answerID": "51740386",
        "updateDate": "2015-06-18",
        "answerCommentCount": 0,
        "answerContent": "民国时中国四大金铺 有一家是邹家的<br>就是我们家 然后随着历史的变迁<br>不准私营了 全部充公了 <br>于是现在的我是一个平凡人<br>嗯 当年真的真的是很有名啊",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic4.zhimg.com/6769e135b_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/51725071",
        "authorName": "大博子大脖子",
        "commitDate": "2015-06-17",
        "authorID": "da-bo-zi-da-bo-zi",
        "answerID": "51725071",
        "updateDate": "2015-06-17",
        "answerCommentCount": "2",
        "answerContent": "祖上是太子的老师，结果太子在九子夺嫡中败下阵来。祖上怕受到牵连就逃到东北避难了～",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/51547198",
        "authorName": "匿名用户",
        "commitDate": "2015-06-16",
        "authorID": "coder'sGirlFriend~",
        "answerID": "51547198",
        "updateDate": "2015-06-16",
        "answerCommentCount": 0,
        "answerContent": "我外公就就是朱八八 下来的应该是岷王后代  到我舅舅就不按照族谱来规定名字了 过世的早 我还没见过",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/51368206",
        "authorName": "匿名用户",
        "commitDate": "2015-06-14",
        "authorID": "coder'sGirlFriend~",
        "answerID": "51368206",
        "updateDate": "2015-06-14",
        "answerCommentCount": 0,
        "answerContent": "曾用姓博尔济吉特<noscript><img data-rawheight=\"553\" data-rawwidth=\"279\" src=\"http://pic3.zhimg.com/38b6470721a08136b2de8980695e9a7a_b.jpg\" class=\"content_image\" width=\"279\"></noscript><img data-rawheight=\"553\" data-rawwidth=\"279\" src=\"//s1.zhimg.com/misc/whitedot.jpg\" class=\"content_image lazy\" width=\"279\" data-actualsrc=\"http://pic3.zhimg.com/38b6470721a08136b2de8980695e9a7a_b.jpg\"><br>现用姓包<br>四代从军，包括我兄弟几人，算是传下来了？",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/51176191",
        "authorName": "匿名用户",
        "commitDate": "2015-06-13",
        "authorID": "coder'sGirlFriend~",
        "answerID": "51176191",
        "updateDate": "2015-06-13",
        "answerCommentCount": 0,
        "answerContent": "三代从戎不知道算不算。 <br>姥爷是海军，参加过80年代洲际导弹试验和中国早期航母论证工作。姥姥是海军护士，护理过叶帅、张学思、陶勇。父亲也是浪花白，从记事起就经常不在家，都是回来才告诉你去哪了。",
        "answerAgreeCount": "1"
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50874693",
        "authorName": "匿名用户",
        "commitDate": "2015-06-10",
        "authorID": "coder'sGirlFriend~",
        "answerID": "50874693",
        "updateDate": "2015-06-10",
        "answerCommentCount": 0,
        "answerContent": "讲一个秀才遇上兵的故事<br>爷爷的爸爸是燕京大学毕业，办过学<br>我爷爷1950年毕业于北师大，在绍兴教了一辈子书<br>我奶奶是大家庭出身算是以前的幼师   也教小学不过结婚以后就不再教书<br>我爸17岁开始在绍兴教初中（那时候政策是必须先工作才能读大学），大学毕业以后来回本地教高中数学（ps：清华北大学生都教出来过，老是说自己教了一辈子的书怎么教出了我这样的儿子TAT）<br>我大伯的儿子也教书<br>我大伯应该代表了我们家教书达到的最高水平，17岁开始教书，然后担任了两个学校的校长，一个学校的副校长加上一大堆的头衔。<br>说说我们家教书人的特点：<br>1.脾气犟，认死理，觉得读书好就是好，千万别说读书人开明。。家里都是我爸说一不二<br>2.节俭：不抽烟不喝酒，没有娱乐活动，每天回家上网看新闻。。。衣服不破不换，我记得有一件白的棉背心我爸已经穿4.5年了，后面拉了一个大洞还是穿着（心酸脸）<br>3.性子急，小的时候做作业，最怕我爸在边上看，有时候做的慢，他就瞪我一眼，我还以为自己做错了，拼命擦了写其它答案。。。结果被暴打一顿。。。<br>4.从小教育不要拿别人东西，一般家里过年，远方亲戚来给我红包我都不能拿，只有大伯姑姑奶奶这些给才能收（ps：连仅有的几个红包收了也是要上缴的TAT），因为我爸一般都是班主任，所以过年陆陆续续有家长来拜年，提些年货虾啊酒啊什么的，有时候推不掉会收，但是给钱的一律退回去，而且一般来拜年的都先打电话，我爸接了就说自己不在家让他们不用来了。<br>5.虽然我爸是教数学的但是有颗文艺青年的心，会写诗（虽然我觉得写的好差TAT），每天还会发日志TAT，昨天他带的这一届学生高考完，今天就发了这样的：<br><strong>清闲自在的一天 </strong>2015-6-10 20:14 <br><br><br>没有学生，没有数式，我是一个自由自在的人。忙碌后的清闲，自在呢还是烦恼，无人能知道！<br>6.你们体验过小学初中高中读的学校里都有老师是我爸学生么TAT   特别照顾的感觉TAT 然后周六周日各种补课 <br>————————————————————————————————————————————————————————————————————————————————————————<br>接下来说说我大伯的事，本来我大伯和我爸在一个高中教课，后来转去另一个高中了（ps要不是我爸年轻的时候脾气不好凭他的资历应该可以做校长了，现在职称是副教授），我大伯脾气也是很直的那种（印象里我爸和我大伯还在同一个高中教书的时候就打了一架，我看着他们打架在偷笑，然后我爸回去痛定思痛，觉得我毕竟是他儿子，越是决定拉着我一起痛，就把我也打了一顿TAT），现在进去了，判了六年，据说原因是教育局里一个领导在饭局上和我大伯说想要他们学校后门的半条街，我大伯说这不是他能决定的就拒绝了那个领导，好像说话直了点，然后过了不久，就被人举报贪污，行贿人是一个卖机器给我大伯学校的，自己投案说给了我大伯5w块钱，放在我大伯办公室的抽屉里（我大伯立过规矩，不能让其它教职工进自己家门），我大伯根本不知道这件事，然后就被直接扣在局里五天，虽然上诉想要翻案，但是不行，我姑姑和我爸每次一上诉往省里跑，市里马上第二天就派人上去疏通关系，这些都是我爸学生说的，零几届的学生吧，好像也在法院上班。北京也去过，不过依旧没有什么卵用。<br>也许有人说：“你大伯肯定收钱了，你只是给自己家人说好话而已。”<br>我也没有什么办法反驳，不过虽然我们家没钱，5w块还是拿的出来的，而且我大伯再过两年就退休了，为了5w犯的着么？<br>我大伯没认罪，被判认罪态度差，加了一年，6年，大概我毕业再一年，我大伯就能出来了<br>我和我奶奶两个人呆着的时候她会抹眼泪，说世道差，说我大伯教了大半辈子的书了，还会说起爷爷的事说起我爸我大伯我姑姑小时候的事<br>然后她会握着我的手叫我好好读书，争气点别给家里人丢脸。<br>等我大伯出来，我们还会继续上诉，我奶奶说读书人，最重要的是有骨气，我们一家人都等着那天",
        "answerAgreeCount": "3"
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic1.zhimg.com/9cdc4fd38_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50822859",
        "authorName": "马一鸣",
        "commitDate": "2015-06-10",
        "authorID": "ma-yiming-21",
        "answerID": "50822859",
        "updateDate": "2015-06-10",
        "answerCommentCount": 0,
        "answerContent": "山西大同人，祖传吹牛逼骗人",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50687829",
        "authorName": "匿名用户",
        "commitDate": "2015-06-09",
        "authorID": "coder'sGirlFriend~",
        "answerID": "50687829",
        "updateDate": "2015-06-09",
        "answerCommentCount": 0,
        "answerContent": "祖传做白事，甚至族谱上有钟馗。<br>我曾爷爷做白事确实赚了很多钱，加上祖上也有很多积蓄，家里有过很多地。不过我曾爷爷好赌，把家里绝大多数的地都输了。（还好输光了。要不然土改划成地主也有得难受。）不过听说他写毛笔字特牛逼，在我们那边很出名。<br>到我爷爷这代，本来是两兄弟可是我小爷爷早逝，我爷爷也不喜欢这个职业，当年认识字的人很少镇上叫我爷爷去教书，我奶奶不放心。（很少能回家，当时交通很不发达。我们那里很落后。）我曾爷爷蛮长寿活到八十多岁，由于我曾爷爷是做白事的即使当年多动荡也经常吃肉。后来我爷爷没有接手这份工作。反而我的四伯做了这个。<br>听我四伯说是由于我们家族必须有一个人从事这个职业，而传承是上一辈做这个职业的人去世，出殡时把他的遗体跟他生前所用的唢呐锣鼓放在家族祠堂关上门。家族里的人在祠堂外等候家族中会有一个人听到做白事的乐声响起。那便是注定要吃着份饭的人了。而我问四伯当时我曾爷爷去世的时候他听到了没有，他却没有回答我。<br>不过我感觉到了我这一代，感觉传承要断了。",
        "answerAgreeCount": "1"
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50648071",
        "authorName": "匿名用户",
        "commitDate": "2015-06-09",
        "authorID": "coder'sGirlFriend~",
        "answerID": "50648071",
        "updateDate": "2015-06-09",
        "answerCommentCount": "3",
        "answerContent": "祖传手艺应该是低调做人。1930年这个时间左右，曾祖父当年来到我现在居住的村子隐姓埋名，姓氏从黄改成了葛。乱世中，曾祖父借钱给他小舅子（爷爷的舅舅）开钱庄，正好遇上国民党当政，通货膨胀，积蓄打了水漂。我曾祖父没有追究，曾祖父后来靠买卖菜油生意为生。我爷爷的时代正好内战建国，他选择当农民，做人规规矩矩。关于姓氏我爸爸只跟我说过一次，我有次单独问爷爷为什么要改，他只字不提，只说那是上辈子的事情了。我爷爷说在他小时候我们家院子每天晚上村里的很多人聚集闲谈，我曾祖父跟爷爷都是属于一群人中安安静静不参与谈话但是洞悉全局的人，没跟任何人有过节。我感觉到我祖上还是有一些秘密的…爷爷年龄也挺大了，这个秘密估计会放在他心底直到老去吧。",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50622178",
        "authorName": "匿名用户",
        "commitDate": "2015-06-09",
        "authorID": "coder'sGirlFriend~",
        "answerID": "50622178",
        "updateDate": "2015-06-09",
        "answerCommentCount": 0,
        "answerContent": "我家祖祖辈辈也都是书香世家，到了爷爷那一带人整个家都没落了，太爷爷几个兄弟，我太爷爷是当时县城书记员（那会儿不叫书记我也不知道咋说），那个年代都穷，我爷爷小時候过年却放的起烟花，我太爷爷过年过节往家拿，可惜30岁的时候病死了，我爷爷那年9岁，没得念书，太奶奶改嫁，成了孤儿。 <br>        太爷爷的弟弟是医生，夜里给人看病的时候他说这病不能去瞧，瞧了他就得偿命，心软经不住求，去了，第二天死在了家里。 <br>       老三，是个教书先生，也是厉害的很，就收了3个学生，都是听一代一代传下来。也是没活过40岁。 <br>唯独老四，平平凡凡的活了三个哥哥加起来的年纪。 家道没落，死的时候孩子都太小了，至今太爷爷那一代人墓碑上都没名字。不记得了。说这些也是跑题，就是想念叨一下。 <br>        爷爷这一代这几个孤儿，放牛赚公分，进城煤矿工，当时工人就是很牛逼了，没人念书了，到了爸爸那一代，也是都普普通通，一直到我，我爷爷说，我算是从他懂事之后第一个大学生了。高中的时候不想念书了，我爷爷追着我爸爸打，骂我爸爸不送我去学校，其实是我自己死活不喜欢那些老师，从那儿以后，再也不会任性不念书，我知道爷爷是真的一个人从9岁养活了一个家，18岁去偷族谱被打出来，姐姐被卖掉，太爷爷走了之后没条件读书，就盼着我们不要像他受苦，老人家节约了一辈子，一直心怀感激。<br>         家里一直重女轻男，作为家里长女唯一的女孩子，今年过年回去给爷爷磕了个头，20多年第一次磕头。我爷说，别忘本，别忘根。<br>         虽然不是大富大贵之家，活在这样的家庭，我三生有幸。",
        "answerAgreeCount": "1"
    },
    {
        "authorSign": "飞面神教虔诚信徒",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic2.zhimg.com/7321507f9_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50617124",
        "authorName": "地高辛Digoxin",
        "commitDate": "2015-06-09",
        "authorID": "di-gao-xin-digoxin",
        "answerID": "50617124",
        "updateDate": "2015-06-09",
        "answerCommentCount": 0,
        "answerContent": "祖传种地<br>然后我爹是恢复高考后第一批农学硕士<br>我好死不死的刚刚农学博士毕业",
        "answerAgreeCount": "1"
    },
    {
        "authorSign": "创业者ing",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic3.zhimg.com/7c12bcaa6_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50419501",
        "authorName": "我去2016",
        "commitDate": "2015-06-07",
        "authorID": "wo-qu-2016",
        "answerID": "50419501",
        "updateDate": "2015-06-07",
        "answerCommentCount": 0,
        "answerContent": "多少没落族，深藏功与名",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50212048",
        "authorName": "匿名用户",
        "commitDate": "2015-06-05",
        "authorID": "coder'sGirlFriend~",
        "answerID": "50212048",
        "updateDate": "2015-06-05",
        "answerCommentCount": 0,
        "answerContent": "奶奶祖上世代教书，小时候总说我们是书香世家。奶奶的爸爸是曾经是当地有名的地主，拥地200亩。家中丫鬟无数，花草无数，鸟儿乌龟猫狗无数。读书人好得就是一个闲情逸致，据奶奶说，共军解放海南前一年，有位风水先生曾来到他们家庭院，说要算上一挂。奶奶的爸爸直接给人赶出家门，回头继续赏花赏鸟。风水先生随后轻声说了句，“种花养鸟，家规坏了（三声）”。果不其然，一年之后，当家的大爷被一枪爆头。<br>奶奶的前任老公是国军最后一期的黄埔军校军官，横行乡里，鱼肉百姓，当然，最后的结局也是直接爆头。<br><br>先这样，有空再更",
        "answerAgreeCount": 0
    },
    {
        "authorSign": "求关注 逗比 童子功段子手 新媒体 全机种游戏制霸 二线中产 鉴黄师",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic2.zhimg.com/14f19e9dd3d0c0909861362809a55a09_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50184468",
        "authorName": "马铁泉",
        "commitDate": "2015-06-05",
        "authorID": "ma-tie-quan",
        "answerID": "50184468",
        "updateDate": "2015-06-05",
        "answerCommentCount": 0,
        "answerContent": "我决定经常看看这个问题，激励一下没落家族长子长孙的复兴斗志。",
        "answerAgreeCount": "1"
    },
    {
        "authorSign": "知无不言，知无，不言。",
        "questionID": "22480996",
        "noRecordFlag": 0,
        "authorLogo": "http://pic4.zhimg.com/2865e5cda3f544c5b3d0666b2e189bab_s.jpg",
        "answerHref": "http://www.zhihu.com/question/22480996/answer/50170789",
        "authorName": "知无不言刘锤锤",
        "commitDate": "2015-06-05",
        "authorID": "zhi-wu-bu-yan-liu-chui-chui",
        "answerID": "50170789",
        "updateDate": "2015-06-05",
        "answerCommentCount": 0,
        "answerContent": "爷爷辈以上基本没听过，听我爸说的。<br><br>也算是个…大宅门的故事吧…有祖宅，挺大的，当年好几房一起住。我爸是嫡孙，按理说宅子该给他但是我爷爷带着他在南京也不常回去，所以那宅子给我爷爷的妹妹家里占了，我爸也没有想回去拿回来的意思。<br>我爷爷祖上也算是个X半城之类的人物…然而………是个木匠…是，没错，木匠！（喂不要小看木匠啊喂！整个城的木匠铺全是我家的啊喂！）那个年代的时候，搞木材还是比较赚钱的，然后我家祖上硬是靠搞木材成了城里首富…家里也算是书香门第，虽然是个木匠然而子女都接受了当时最好的教育了。<br>然而到我太爷爷这辈疏于管理，并且家里偏房啊亲戚太多，就有点四分五裂了。而且吧我爷爷那一辈的哥儿啊爷们都是提笼架鸟的主儿，天天吃喝玩乐，铺子都给了大奶奶（我爸他奶奶）打理，后来老人家岁数大了，正好那时候也正赶上那啥嘛，铺子都没留住（我们家明明就是个木匠啊喂！不是地主啊喂！没收这些干嘛啦！）然而大奶奶机智的把黄金还有很多钱放罐子里藏在树根下啦。后来风头过了一大家子就靠这几罐子过日子。粮食那简直有价无市，罐子里的硬货就越来越少啊，后来无力支撑家里几十口人和那么大个宅子的打理，就败了，或者说从收铺子开始就已经败了。<br>我爷爷也没有想要重新捡起祖上传下的活儿的打算。于是去了南京，老爷子也是挺传奇的…文革前在铁路局混的顺风顺水成了大领导，听我爸说他小时候出门都是车接车送，想买啥买啥，后来……X革老爷子站队出了事儿，就被弄进去了…家里就树倒猢狲散，老部下啊老邻居都只能表达一下精神上的安慰，实质上谁都没帮忙，房子都给收了，我奶奶带着几个姑姑和我爸过日子挺辛苦了，后来我爸接受不了那种从天堂掉地狱的生活，变得脾气特别暴躁，打架都下死手那种。后来我爸挺大了我爷爷才放回来，回来就各种补偿，我爸都没搭理他，那时候铁路局来人请我爷爷回去官复原职甚至更高，我爷爷都不去了，就只当个主任，天天蹲家里。<br>我挺小的时候爷爷就去世了，但是我记忆里老爷子脾气特别硬，永远都特别严肃，因为只有我算是真正家里的嫡系了，特别疼我，（我姑姑们现在也经常说我家XXX就你这一个咱们老刘家的人了。）然而我那时候小跟我爷爷一直距离不近，但是我爷爷每次看到我出手都特别大方，每次那毛爷爷给的简直了。然而那时候老爷子已经肺癌晚期了，他竟然还能刻个木头出来，也算是不负家传吧。哦貌似老爷子随手刻的那个木头画拿了全国金奖。<br><br>据我爸说他奶奶就是特别看重嫡庶还重男轻女，可能老时候大户人家都是这样，就是一大桌菜我爸一个人吃，平常满街窜要什么吃什么，我爸都饱了…，他几个堂兄弟饿的眼睛都发绿也只能站一边看他吃，我爸有次叫他们来吃，小男孩嘛都不大，推了下就过来吃了，正好大奶奶看见。除了我爸，全罚跪了，特别狠心，跪了一整天。<br><br>唉大户人家后期就是，家里都没钱了还得要硬撑着面子，实际上工人的钱都扣的特别紧了，对外还是死要面子，买买买那种。<br><br>我爷爷去世的时候我看过一次老家来的人，据说是我爷爷的妹妹，那真是，唯唯诺诺的，没有主心骨的样子，我太爷爷在的时候听太爷爷的，大奶奶在的时候听大奶奶的，大奶奶不在就全听我爷爷的，我爷爷不在就都听我爸的………据说那时候养得来的女孩子就是这样……………<br><br>有次我问我爸能不能把咱家宅子收回来，就算不住把东西卖卖都是分分钟全是钱啊，那些个雕花，那些个檀木，咱家到底是搞木材的，家里一水的都是好木头阿，随便拎个板凳出来都比现在外面买的什么红木家具好多了。<br><br>可惜败了就是败了，我爸说可怜他姑姑还是好几房的堂兄弟什么的，都住宅子里呢，收了他们怎么办，后来我就再也没问过了。",
        "answerAgreeCount": "1"
    }
]